name: .NET 5 CI
on: [push]

jobs:
  build:
    runs-on: windows-latest
    name: EditInC1
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.302' # Check for latest at link below
      - run: dotnet build